// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Regulator.Client.Data.Contexts;

#nullable disable

namespace Regulator.Client.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250919115912_AddUploadedFiles")]
    partial class AddUploadedFiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("Regulator.Client.Data.Models.DownloadedFile", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Hash");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Regulator.Client.Data.Models.UploadedFile", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT");

                    b.HasKey("Hash");

                    b.ToTable("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
