name: Build Auth Service Docker Image

permissions:
  id-token: write
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::886436922604:role/github-actions-role
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build Docker image
        run: |
          docker build -f Regulator.Services.Auth/Dockerfile -t regulator/auth-service:${{ github.sha }} .
      - name: Tag Docker image for ECR
        run: |
          docker tag regulator-services-auth:${{ github.sha }} ${{ steps.login-ecr.outputs.registry }}/regulator/auth-service:${{ github.sha }}
      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/regulator/auth-service:${{ github.sha }}
